import "./globals.css";
import Header from "../components/Header";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className="min-h-screen bg-yellow-100 flex flex-col">
        <Header />
        <main className="flex-1 w-full">{children}</main>
      </body>
    </html>
  );
}